[project]
name = "langfuse-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "docling>=2.126.0",
    "langchain>=1.3.18",
    "langchain-aws>=1.7.5",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.1",
    "langchain-docling>=3.0.0",
    "langchain-text-splitters>=1.1.2",
    "langfuse>=4.15.1",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
langfuse_experiment = "langfuse_experiment.main:main"

[build-system]
requires = ["uv-build>=0.4.0,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["."] # So that tests can call 
